### ISSUE TITLE
Please add support for new Draenor Lures

### ISSUE THREAD

**Issue by MetaverseJosh** [UltimateFishbot/UltimateFishbot#10]
In addition to lures such as sharpened hooks and worms, there is now a second lure or "bait" in the game that can be used simultaneously and only lasts for 5 minutes.  Can we have support added for adding a second type of lure on button 3 with a duration of 5 minutes?

**Comment by henrikhermansen** [comment]
I've made these changes in my fork. I need to test them first, but I expect to open a pull request tomorrow. I've already opened #11 with changes made for MoP by someone else. Charm isn't useful anymore in WoD, but the fishing raft shortkey should be.

**Comment by henrikhermansen** [comment]
#14 is now created @captainloozer :)

**Comment by MetaverseJosh** [comment]
Thank you!
