### ISSUE TITLE
Fishbot.exe not launching

### ISSUE THREAD

**Issue by trinoan** [UltimateFishbot/UltimateFishbot#101]
Tried all three of the latest versions of fishbot.exe, and none of them open/run/launch. 

Error logs all show the same: 

Faulting application name: UltimateFishBot.exe, version: 1.0.0.0, time stamp: 0x54c22e8c
Faulting module name: KERNELBASE.dll, version: 10.0.15063.674, time stamp: 0x6d16dd24
Exception code: 0xe0434352
Fault offset: 0x000eb872
Faulting process id: 0x46c
Faulting application start time: 0x01d36cf2ecc601f8
Faulting application path: C:\xxxxx\Desktop\UltimateFishBot.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: ee5c2f17-59e9-4ce3-af02-320a6ec5eef9
Faulting package full name: 
Faulting package-relative application ID: 

Application: UltimateFishBot.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at CoreAudioApi.Interfaces.IMMDeviceEnumerator.GetDefaultAudioEndpoint(CoreAudioApi.EDataFlow, CoreAudioApi.ERole, CoreAudioApi.Interfaces.IMMDevice ByRef)
   at CoreAudioApi.MMDeviceEnumerator.GetDefaultAudioEndpoint(CoreAudioApi.EDataFlow, CoreAudioApi.ERole)
   at UltimateFishBot.Classes.BodyParts.Ears..ctor(UltimateFishBot.Classes.Manager)
   at UltimateFishBot.Classes.Manager..ctor(UltimateFishBot.frmMain)
   at UltimateFishBot.frmMain..ctor()
   at UltimateFishBot.Program.Main()

Fault bucket 94671623643, type 5
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: UltimateFishBot.exe
P2: 1.0.0.0
P3: 54c22e8c
P4: CoreAudioApi
P5: 1.0.0.0
P6: 462cc929
P7: 6b
P8: 2
P9: PSZQOADHX1U5ZAHBHOHGHLDGIY4QIXHX
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER751B.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER757A.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER75A3.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER75B3.tmp.txt

These files may be available here:
C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_UltimateFishBot._4ec8d3ecf559797c6649a71de70646f3d4ada2_df23f1c3_8c737d2a

Analysis symbol: 
Rechecking for solution: 0
Report Id: ee5c2f17-59e9-4ce3-af02-320a6ec5eef9
Report Status: 268435456
Hashed bucket: a7436c01dede211905e5b326147a08af

**Comment by Dunkr23** [comment]
Going to sound weird, but change the name of the folder the .exe is in (add a 1 or something at the end). I was having a similar issue and this fixed it.

**Comment by NaNraptor** [comment]
If @Dunkr23 's suggestion did not work, please try the latest version of the bot
