### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by aphrasion** [UltimateFishbot/UltimateFishbot#102]
i press start and my cursor goes to the top left corner of my monitor
i have it in windowed mode and i have the process name correct (i think)
would love to have a fix, i need to make some money
thanks

**Comment by ilikefish** [comment]
I'm also having the same issue.

I've tried running this in the different compatibility modes and as administrator. I can't seem to get this working.

I'm using this on a private server - version 2.4.3
I'm running Windows 10 as well.

Would love to have a fix for this! Thanks in advanced!

**Comment by hijacker81** [comment]
Finally an .exe that works... sort of...

I'm having the same issue as above.
I hit start and the cursor goes the top left corn er of the screen.

which results in having no target.

**Comment by ilikefish** [comment]
I've gone through the previous version and it wasn't till 4.0.27, that the mouse pointer went to the top left hand corner of the screen.
Other versions previous to that simply kept trying to fish constantly and not scan / search for the bobber.

**Comment by juggenizer** [comment]
I can verify this and also verified fix for it. For all occurances of IntPtr Wow = FindWindow("GxWindowClass", "World Of Warcraft"); You should change to IntPtr Wow = FindWindow(null, "World Of Warcraft");

After that everything works, this was also a issue where the "click/loot" didn't work because of this

**Comment by NaNraptor** [comment]
fixed in v4.5.0.0 (and many versions before that too :) )
