### ISSUE TITLE
Initial splash too loud?

### ISSUE THREAD

**Issue by TStevens13** [UltimateFishbot/UltimateFishbot#103]
After casting the fishing spell, there is a quiet splash, but under the Audio Devices settings the splash will remain at usual values but often it will spike to 80-90. Setting the threshhold to 90 keeps it from clicking immediately after the cast, but stops it from recognizing the actual splash for the fish even though the real splash reaches 99.

I have tried reducing the Master Volume in WoW to 50% and reconfiguring the settings to lower values, as the difference from initial splash to real splash is then ~50. but it still does not click the bobber when a fish is caught.

After some testing it appears that on casts where it works correctly there is only one jump in volume according to the settings, but when it spike super high, it has an initial reasonable spike, and then a secondary very loud spike. I do not hear this spike in game, and I do not know where it could be coming from.

This is only a recent problem and any help would be great.

**Comment by Gasur** [comment]
["It is very important to note, that the game volume and the volume in the bot settings has to cross. Meaning if the bot setting requires the volume to be at 80%, and you have your game volume on 20%, it will never reach that threshold. A good way of debugging it, is take Windows volume to max, game volume to max & bot setting to 1 or any low number."](https://github.com/UltimateFishbot/UltimateFishbot/issues/78#issuecomment-219387776)

**Comment by Gasur** [comment]
Also referencing the bug [here](https://github.com/UltimateFishbot/UltimateFishbot/issues/52#issuecomment-131583756), and the replies from the developers [here](https://github.com/UltimateFishbot/UltimateFishbot/issues/52#issuecomment-133242474).

**Comment by NaNraptor** [comment]
Most likely fixed in latest version - if you still have a problem raise the issue again
