### ISSUE TITLE
Windows title

### ISSUE THREAD

**Issue by KillerBoy001** [UltimateFishbot/UltimateFishbot#114]
The last few reports you have bene receiving of banns are probaly due to the windows title. 
yes they do check runing programs etc 

ide say make it something less obvious like "Setup"  or "Chrome" the way this works is still very much safe but ... the title nor .exe name is ...

**Comment by fooyoo1** [comment]
An option to change the title would be nice, so if that was to be added it would be the easiest way for people to set a new name on it.  They do give the source tho, so you can change it to whatever you like and compile it too.  If the name was set to something and the exe posted here, there is no reason to believe they would not just look for that name as well.

**Comment by Gasur** [comment]
The whole code is opensource and is rather trivially to change the window title. Warden will simply look for something else. It isn't stupid and only looks for windows names or signatures. It is much more sophisticated.

**Comment by KillerBoy001** [comment]
exacly but then they will have to start looking at something else. Thatst the whole point. 
I mena if i learned one thing im my years as a game hacker and software developer that it to randomize stuff .. 

they cant get a grib on stuff thta is randomized .. 
Button timers , press timers, timeouts. 
As less static stuff as possible makes them have les and less to look for.

**Comment by Gasur** [comment]
You do not understand how big games anti cheating system works then. Changing window title will do practically nothing.

**Comment by KillerBoy001** [comment]
I ave been working with a reasonable few of them so ... 

They do check active windows based on titles combined with window classes will lead to a ban, been there done that.
so yes it does help. 

its like saying when you commit thievery  there is no need to hide my true name since they wont look for it anyway. 
but they will grab you on anything they can find . every bit helps. 
I know for one im changing the handles and evrything i can but not everybodu had teh knowledge to do so.

**Comment by Gasur** [comment]
You are misunderstanding me. If this software is in their searchlights then changing the window title will do nothing, as that is not the only thing they are checking. If you want to stay undetected you need to do much more than just change the window title.

**Comment by KillerBoy001** [comment]
yes offcourse. 

Though im just saying Warden does log every opened window.
If by any change they ever checked you out for ahtever reason maybe routine etc and they noticed a windows beeing opened called "Ultimate Fishingbot" do you think they will let this go ? 

Im not saying its the only thing they log or they sign a program on.

But i bet you now that one day a person will be banned cause some employee @ blizz Noticed a open window called Fihingbot while running routine checks...

**Comment by daniel-widrick** [comment]
After digging through this a bit, setting the window title dynamically is trivial. Hiding more complicated things like the .exe name and assembly name becomes a major issue related to the way CSHARP is architected. 

Taking the issue to its logical conclusion in the arms race, all blizzard has to do is hash the running .exe file and compare it to reported botters. That becomes a more difficult problem to solve.

**Comment by NaNraptor** [comment]
Similar to #124 - closing this one
