### ISSUE TITLE
Sound detected in meter, yet no command in clicking bob. 8.0

### ISSUE THREAD

**Issue by Quixo1E** [UltimateFishbot/UltimateFishbot#119]
Currently in 8.0, the program does not detect the sound of the bob. Perhaps it is just for me but the volumes are synced, at least according to the meter in the program.

**Comment by billi95** [comment]
have the same problem. the bobber jumps, the sound goes up but no command from the bot to click it

**Comment by NaNraptor** [comment]
You probably have the splash threshold value too high, set it to something lower. If this was a bug in the code it will most likely be addressed already in the latest release
