### ISSUE TITLE
Location of the config file

### ISSUE THREAD

**Issue by petrvecera** [UltimateFishbot/UltimateFishbot#120]
I am getting crash report after changing the config (selecting different audio device). Every-time I start the program, it crashes now.  

Where is the config file located? I can't find it anywhere. 

Thanks

**Comment by NaNraptor** [comment]
Rebuild from source. I am not sure what you mean by "cant find the config file"

**Comment by NaNraptor** [comment]
I think I understand what you mean now.

 The default settings are stored withing the binary itself

The changes you make are saved somewhere within appdata/roaming or appdata/local in a folder which contains a user.config file

**Comment by petrvecera** [comment]
Yes I was looking for this:
>The changes you make are saved somewhere within appdata/roaming or appdata/local in a folder which contains a user.config file

If anyone needs this, just search up  in `%localappdata%` I found it in `C:\Users\pagep\AppData\Local\Open_Source\UltimateFishBot.exexxx`

Couldn't find before it. Anyway I solved the problem by rebuilding it cos I also needed to do some code changes - somehow sending the right click mouse event to my wow process doesn't work. Using Windows 10 and wow woltk client (it's a custom client might be related) - anyway I changed the right click to simply simulate right click in Windows itself, which is quite handy because you can move with the mouse itself and "help" the bot, if you are around - cos I hookup the bot and wow to 1 sound interface and watch youtube on another one.
