### ISSUE TITLE
Ban is all because of the report?

### ISSUE THREAD

**Issue by johnnygodsa** [UltimateFishbot/UltimateFishbot#122]
What I want to know is
Are most people getting ban because they are being reported?
Instead of the program being detected?

**Comment by daniel-widrick** [comment]
I haven't seen mass reports of bans. Either way, it's probably a combination of players getting reported and then Blizzard running metrics and finding others.

**Comment by NaNraptor** [comment]
More measures to stay undected have been added, will release the latest version (4.5.0.0) soon
