### ISSUE TITLE
Some ideas for safer bot

### ISSUE THREAD

**Issue by kamil234** [UltimateFishbot/UltimateFishbot#124]
Since blizz scans processes outside of its own memory, there are few changes that can be made to make this safer:

1. make the delay between casts / looting random (able to input something like 1500-6000, instead of static value)
2. use a 'launcher' to launch the exe with randomly generated process and window name
3. may be overkill, but add some garbage strings or metadata on exe launch to generate unique program hash every time

**Comment by daniel-widrick** [comment]
I've looked into 2. It's a pretty complex undertaking in c#

**Comment by daniel-widrick** [comment]
1. handled
2. Window names have been adjusted but process names are more difficult.
3. Above my pay grade for sure.

https://github.com/daniel-widrick/UltimateFishbot/releases/tag/Fishbot-4.4.00

**Comment by kamil234** [comment]
Thanks Daniel. Appreaciate your work!

**Comment by NaNraptor** [comment]
1. In latest pull request it's handled even better - the user can specify a range now, for a number of values

**Comment by Lunat1q** [comment]
2. Launch with random name:
Create simple console-type launcher.
```
    class Program
    {
        private const string ExeExt = ".exe";
        private const string DefaultName = "UltimateFishBot.exe";

        static void Main(string[] args)
        {
            var lastName = Properties.Settings.Default.UFBName;

            if (!RunBotSecretly(lastName)) RunBotSecretly(DefaultName);
        }

        [DllImport("user32.dll")]
        static extern int SetWindowText(IntPtr hWnd, string text);

        static bool RunBotSecretly(string name)
        {
            var ufbExeFile = new FileInfo(name);
            if (ufbExeFile.Exists)
            {
                var newName = StringUtils.RandomString(12) + ExeExt;
                File.Move(name, newName);
                Properties.Settings.Default.UFBName = newName;
                Properties.Settings.Default.Save();
                var p = Process.Start(newName);
                Thread.Sleep(1500);
                SetWindowText(p.MainWindowHandle, newName);
                return true;
            }
            return false;
        }
    }
```

**Comment by daniel-widrick** [comment]
@Lunat1q , would you be willing to submit a working pull request to my or @NaNraptor 's fork? I've played with this and encountered issues. As an aside, this launcher code can probably be simplified to exclude the user32 libraries as we are generating the window title dynamically in code on the development forks.

**Comment by NaNraptor** [comment]
I see how that can work, @daniel-widrick  I know it might be a silly question but did you add the `UFBName` to `Properties.Settings.Default` I havent tested it yet as I am at work, but will test later tonight.

Edit: @daniel-widrick also check my request pull's comment about the GUID used to expose the bot's COM objects - what do you think about that issue?

**Comment by Lunat1q** [comment]
I'm currently working on some other improvements, so, may be later.
![image](https://user-images.githubusercontent.com/16973172/44927551-9ea55800-ad5d-11e8-930f-a283a07bae17.png)
Currently it's working like that:
tstarting with default name -> rename to random -> remember new name -> start

second start -> restore previous random name -> change -> remember -> start

etc...

**Comment by Lunat1q** [comment]
Also: https://stackoverflow.com/questions/2031217/what-is-the-fastest-way-i-can-compare-two-equal-size-bitmaps-to-determine-whethe

instead of:
ImageCompare method.

**Comment by Lunat1q** [comment]
@daniel-widrick  may be we can create Discord server to discuss all possible improvements? I have some experience in bot dev :) and clearly see some spots to improve.

**Comment by NaNraptor** [comment]
@Lunat1q would you mind creating one and posting an invitation link?

**Comment by NaNraptor** [comment]
Mistakenly closed the issue

**Comment by Lunat1q** [comment]
@NaNraptor https://discord.gg/upeqJc5

**Comment by Lunat1q** [comment]
#131 PR for 1 (added randomization in clicks) and 2 (added launcher)

**Comment by Lunat1q** [comment]
pt.3 looks a bit impossible without reflection stuff, all we can do is create some mock dynamic classes. OR use tool like [Confuser.EX](https://github.com/yck1509/ConfuserEx) which will translate entire bot code to unreadable garbage

**Comment by NaNraptor** [comment]
Closing this issue as suggestion 1 has already been included in latest release, No 2 will be included in the next one which will be released either today or tomorrow. And for now we have decided to stay away from No 3 as it will require way too much work

**Comment by NaNraptor** [comment]
Apparently I cannot click buttons.... Closing again
