### ISSUE TITLE
Fishing bot 4.3.00 doesn't work

### ISSUE THREAD

**Issue by billi95** [UltimateFishbot/UltimateFishbot#125]
after daniel-widrick commented on #107 I, as instructed, downloaded the newest version of the mod 4.3.00

the moment I try to start the application I get an error almost instantly

![ultimatefishbot_2018-08-23_00-46-34](https://user-images.githubusercontent.com/42515876/44494934-27413b80-a66e-11e8-9d18-6438713d073c.png)

with the following details:
************** Ausnahmetext **************
System.ArgumentException: Die StartStopHotKey-Eigenschaft konnte nicht aus ihrem Standardwert erstellt werden. Fehlermeldung: Der angeforderte Wert "Ctrl" konnte nicht gefunden werden.
   bei System.Configuration.SettingsPropertyValue.Deserialize()
   bei System.Configuration.SettingsPropertyValue.get_PropertyValue()
   bei System.Configuration.SettingsBase.get_Item(String propertyName)
   bei System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   bei UltimateFishBot.Properties.Settings.get_StartStopHotKey() in F:\Sandbox\Development\Windows\UltimateFishbot\UltimateFishBot\Properties\Settings.Designer.cs:Zeile 595.
   bei UltimateFishBot.frmMain.ReloadHotkeys() in F:\Sandbox\Development\Windows\UltimateFishbot\UltimateFishBot\Forms\frmMain.cs:Zeile 142.
   bei UltimateFishBot.frmMain.<frmMain_Load>d__3.MoveNext() in F:\Sandbox\Development\Windows\UltimateFishbot\UltimateFishBot\Forms\frmMain.cs:Zeile 52.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3132.0 built by: NET472REL1LAST.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
UltimateFishBot
    Assembly-Version: 4.3.0.0.
    Win32-Version: 4.3.0.0.
    CodeBase: file:///D:/Downloads/UltimateFishBot-4.3.00/UltimateFishBot/UltimateFishBot.exe.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3151.0 built by: NET472REL1LAST_B.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
Serilog
    Assembly-Version: 1.5.0.0.
    Win32-Version: 4.3.0.0.
    CodeBase: file:///D:/Downloads/UltimateFishBot-4.3.00/UltimateFishBot/UltimateFishBot.exe.
----------------------------------------
System.Runtime
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll.
----------------------------------------
Serilog.FullNetFx
    Assembly-Version: 1.5.0.0.
    Win32-Version: 4.3.0.0.
    CodeBase: file:///D:/Downloads/UltimateFishBot-4.3.00/UltimateFishBot/UltimateFishBot.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Collections
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Collections/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Collections.dll.
----------------------------------------
System.Runtime.Extensions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Extensions/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.Extensions.dll.
----------------------------------------
System.Linq
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Linq/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Linq.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3160.0 built by: NET472REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.IO
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.IO.dll.
----------------------------------------
System.Globalization
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Globalization/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Globalization.dll.
----------------------------------------
System.Threading
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Threading/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Threading.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Speech
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Speech/v4.0_4.0.0.0__31bf3856ad364e35/System.Speech.dll.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
System.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.resources.dll.

The bot window itself looks like this:
![image](https://user-images.githubusercontent.com/42515876/44494999-68395000-a66e-11e8-9a32-31f1ee35465d.png)

everything is empty
![image](https://user-images.githubusercontent.com/42515876/44495037-8606b500-a66e-11e8-8862-2c27ee2d071a.png)

an the drop down menu is buggy too
![image](https://user-images.githubusercontent.com/42515876/44495050-97e85800-a66e-11e8-99d4-49827248495f.png)

**Comment by NaNraptor** [comment]
Revert to the previous version?

**Comment by NaNraptor** [comment]
Was addressed, closing for now. @billi95 if you still have a problem raise the issue again
