### ISSUE TITLE
Public Release 4.5.0.0 no exe?

### ISSUE THREAD

**Issue by billi95** [UltimateFishbot/UltimateFishbot#133]
I downloaded the mod but inside of it there is nothing to start or click on...
maybe I am to stupid but all I find is some strange .sln data

![explorer_2018-09-02_02-50-24](https://user-images.githubusercontent.com/42515876/44951099-186f3b80-ae5b-11e8-8f1a-e3d8023dc35a.png)
![explorer_2018-09-02_02-50-19](https://user-images.githubusercontent.com/42515876/44951100-186f3b80-ae5b-11e8-8230-5d05ec0b88b6.png)

**Comment by NaNraptor** [comment]
Did you click on the clone/Download button? That gets you the source.

To get the exe file go to https://github.com/UltimateFishbot/UltimateFishbot/releases/tag/4.5.0.0

Then under Assets click on the first zip file
