### ISSUE TITLE
Request Inhome  Streaming support

### ISSUE THREAD

**Issue by mufflon11** [UltimateFishbot/UltimateFishbot#136]
Hey , is it possible to add support for Splashtop and or Steam in home streaming  ?
"botting" on a streamed game prevents you from blizzards warden system , and you cant get banned so easy 
Thanks =)

**Comment by CommitCrime** [comment]
Nice idea to prevent detection. I occasionally play with Steam's inhome streaming.

**Comment by Lunat1q** [comment]
Install teamviewer?:)

**Comment by NaNraptor** [comment]
using teamviewer works for now :). Will be considering this feature in the future though
