### ISSUE TITLE
Hearthing failure

### ISSUE THREAD

**Issue by bpalguta** [UltimateFishbot/UltimateFishbot#137]
Hearthing after the alotted time has now failed to complete after multiple sessions. The final line of the log is 
2018-09-02 21:14:53.861 -07:00 [Information] Send key start: 3

however, it does not appear to complete.

**Comment by NaNraptor** [comment]
I haven't even used that feature which us a shame... I will see what I can do

**Comment by NaNraptor** [comment]
When I try and do it, it seems to work just fine. Could you provide a bit more details?

**Comment by bpalguta** [comment]
Unfortunately I don't have any more info. I have not been online to fish since I posted this and it was happening while afk fishing

**Comment by sp3sh** [comment]
Make sure your anti-afk is not lining up with your hearth because it will stop it.
