### ISSUE TITLE
Fishing bot not working / Error with settings

### ISSUE THREAD

**Issue by Ephaltes** [UltimateFishbot/UltimateFishbot#138]
Hello,

When I start the bot it just casts the fishing rod but never picks it up.
I also followed the steps in the guide (sound volume, screen size etc.)

then when i want to open the settings tab i get the following error

https://pastebin.com/SLkGA3rv

all in all cant use the bot

**Comment by NaNraptor** [comment]
I'm unable to reproduce this issue. Clicking on the settings tab works just fine. Could please try to compile from source?

**Comment by jonibahu** [comment]
hi im having the exact same issue


if i open settings the same error pops up.

any help would be appriciated


PS: sadly im too stupid to compile it myself :( 
but the one uploaded here does this weird error when u try to open Settings tab, Windows 10 64bit.

**Comment by NaNraptor** [comment]
Could you screenshot your screen please?

It would be useful to see if it works if you compile it yourself. I can walk you through it step by step. 

Stating with installing visual studio community from the official Microsoft website

**Comment by jonibahu** [comment]
https://imgur.com/a/MPK7gJ3 here 
my error is in german since i use german windows


the settings wont save after i press "save" and the error appears once more 

PS version 3 works without issues

edit: ive managed to find out something more.

When you first open the settings it complains about the "startstophotkey"
when u try to save, it compains about the entry sign format??????!

idk if that helps, but maybe set another start stop hotkey (maybe its not avalible on german keyboards or idk) 

also cant seem to change language (the language files are in "resources" and ive also copies them into the bot folder itself, still nogo)

**Comment by NaNraptor** [comment]
First interesting thing I noticed is the directory name. It contains a path that says users/Nanyo.nanev.jr/Downloads... This is VERY weird it means it searching for something that isn't there... Let me run a few more tests and I will get back to you

**Comment by NaNraptor** [comment]
Also could you copy paste your ufb.log file here? 

Update: please try using the latest pre-release and let me know how that goes. I am still unable to reproduce the bug

**Comment by NaNraptor** [comment]
I believe this is the same issue as #125 and #135. For some reason the settings cannot be read. Could all users with this issue delete the following folder completely?

`%appdata%/../local/open_source`       ---> type this in your address bar in your file explorer.

**Comment by jonibahu** [comment]
2018-09-03 15:54:33.634 +02:00 [Information] UltimateFishBot Started
2018-09-03 15:55:18.374 +02:00 [Information] UltimateFishBot Started
2018-09-03 15:57:19.449 +02:00 [Information] UltimateFishBot Started
2018-09-03 15:58:40.925 +02:00 [Information] UltimateFishBot Started
2018-09-03 16:00:22.801 +02:00 [Information] UltimateFishBot Started
2018-09-03 16:04:08.352 +02:00 [Information] UltimateFishBot Started
2018-09-03 16:04:48.916 +02:00 [Information] UltimateFishBot Started
2018-09-03 16:05:12.766 +02:00 [Information] UltimateFishBot Started
2018-09-03 19:08:28.788 +02:00 [Information] UltimateFishBot Started
2018-09-03 20:16:23.881 +02:00 [Information] UltimateFishBot Started
2018-09-03 20:19:27.061 +02:00 [Information] UltimateFishBot Started
2018-09-03 20:25:37.523 +02:00 [Information] UltimateFishBot Started
 i think this is the log



I tried deleting C:\Users\joniw\AppData\Local (open_source)
but the folder does NOT exist at all
only appdata/local is present, the folder open_source was never made....


maybe this infomation helps figure out the issue

i will use the recommended version and report back


Edit: narrowed it down even further but still no solution sadly
v 4510 (newest) has the same issue, clicking on settings makes the error pop up.

v4101 (the older version) makes the error pop up as soon as you run it, without going into settings. (settings will make it also pop up)



so maybe this helps

edit2: v 4500 (the one used initially) still/also bugs at settings, just had to reconfirm.

and v 4036 doesnt bug at all, the settings are fine there


edit3: my theory LaBlazer's code started/causes the issues, and updates fixed the error on launch, somehow it still comes up when starting settings. 

would be great if we get this working =)

**Comment by NaNraptor** [comment]
Hmm interesting. Could you provide the new complete error log? I suspect the issue is slightly different now and it help seeing what the error log says.

**Comment by jonibahu** [comment]
https://imgur.com/a/wf8LyT9

the top box (i cannot copy paste) says translated something like  : 
The startstopkey couldnt be created from the standartvalue. Errormessage: the requested value "Ctrl" couldnt be found.

which is the exact same message, v4500 had

this is with v4501

here is what it says when i open "details" 
this is what OP posted, i copy pasted it on pastebin (like he did, not to make the scroll that long)

https://pastebin.com/5b8MqE8Q

and for the UFB log 

2018-09-04 11:14:22.295 +02:00 [Information] UltimateFishBot Started

**Comment by NaNraptor** [comment]
@daniel-widrick seems to be right, it should be something to do with your keyboard layout. I will try a workaround, that fixes this specific issue for you. But expect less functionality, until I figure out how to properly fix it

**Comment by NaNraptor** [comment]
I added an additional file to the v4.5.1.0 release. For your convenience here is the [link](https://github.com/UltimateFishbot/UltimateFishbot/releases/download/4.5.1.0/UFB-4.5.1.1-Compability.zip)

Let me know if that fixes the bug

Also check for this folder AGAIN as it might have been created and it is important that it isnt there, for the purpose of this test.

**Comment by jonibahu** [comment]
Hi

Thank you very very much for taking the time to fix this issue.

The verison you posted works perfectly.

I hope you will keep that as "default" version from now on :P 

PS: i noticed it doesnt rename the window properly, but i figured its "on purpose" because its a testversion?!

**Comment by NaNraptor** [comment]
Yes that's on purpose. I have not included all other features just for testing :)
