### ISSUE TITLE
Won't cast

### ISSUE THREAD

**Issue by thegridsquare** [UltimateFishbot/UltimateFishbot#139]
I've done everything right, but the bot does not cast.  I can run it and it just starts searching for 21 s, then searches again.  No matter what key I use to cast, it isnt working.

**Comment by jonibahu** [comment]
can you open settings or do you get an error?

**Comment by thegridsquare** [comment]
I can open settings, everything seems to work EXCEPT it won't cast.

**Comment by thegridsquare** [comment]
What I noticed is the moment I start it, my entire keyboard doesn't work.  I am running 4.3.0 that I got directly from the website.

**Comment by NaNraptor** [comment]
Could you try with the latest pre-release? I just put it up. Also keep in mind that the WoW window will have to be the active window (so no other windows on top of it).

**Comment by kamil234** [comment]
@NaNraptor i just tried the pre-release you provided. Basically, if the option "use lure every X..." is NOT checked, the bot won't cast. If you CHECK the box, and restart the bot, it works fine.

**Comment by thegridsquare** [comment]
Two things, sorry cuz I'm new to github....
1.  How do I download the new version?

2.  On the previous one I am using now, I clicked the "Use lure every X minutes" and it started casting.  Now it won't click when the fish bite.  I have the sound turned up in game, so no idea.

**Comment by Joelyboy** [comment]
Hey i have the same problem

Start 

then the hand just searches

no casting

cast action is on 1 in wow action bar

is this a problem for many or just few?

**Comment by NaNraptor** [comment]
To download the newest release go to the releases tab https://github.com/UltimateFishbot/UltimateFishbot/releases
Then get the latest version. 

Also for the bot to cast, you will have to make sure that WoW is the active window!! This is very important! This means that there must be NO other windows on top of wow while fishing

**Comment by thegridsquare** [comment]
Using your newest version, still having the issue.  Casts, finds the bobber, but with my sound cranked up...the bot is still not catching the fish once the bobber hits.

**Comment by NaNraptor** [comment]
Could you screenshot your in game sound settings?

Press escape, go to 'system' then 'sound' and screenshot

**Comment by thegridsquare** [comment]
![sounds](https://user-images.githubusercontent.com/42944627/45033255-90836000-b019-11e8-9bc0-a0b57efc89ec.png)

**Comment by NaNraptor** [comment]
This might be a problem with your specific sound card then... In the bot settings, could you let me know what your sound threshold value is? For me any value between 15 and 50 works (20-25 works best). If nothing works could you set the threshold to 1? (not 0)

I can't see any error in the code that would miss the sound. We are however using an old sound library that the original author of the bot implemented. So it's possible that your sound card is not supported. If that is the case we begin thinking about switching the sound library

**Comment by Joelyboy** [comment]
Hey all I got it working perfect.
All I did was enable cast lure

Have cast in action 1 and I have the pandaren rod wich can be cast as a
lure buff

It all works but apart from casting the rod..  Don't know if the lure needs
to be on action bar for it to work Or not but hey. Ain't touching a thing
now lol

Cheers hope uz all get it working

**Comment by thegridsquare** [comment]
Let me play with sound in the morning, will link what I find.

**Comment by NaNraptor** [comment]
Seems like @thegridsquare has fixed his issue. Closing
