### ISSUE TITLE
Error: WoW not open

### ISSUE THREAD

**Issue by Crystalleaf** [UltimateFishbot/UltimateFishbot#140]
I can't open UltimateFishBot.exe as it says "Could not find the WoW process....". But I already opened the game. I use CN battlenet and windows 10.

I find this issue: https://github.com/UltimateFishbot/UltimateFishbot/issues/17
In my Windows Task Manager the wow process is called Wow.exe with the description "World of Warcraft".

**Comment by NaNraptor** [comment]
The method we use to get a handle to the window uses the window's TITLE. Are you playing on official servers with the official client?

Please go to system settings and make your game in windowed mode. This will allow you to see the the window title in the top left corner. 

Once you do that, could you please screenshot your screen?

**Comment by Crystalleaf** [comment]
Yes it's the official client.

The title is "魔兽世界” which is the Chinese of World of Warcraft..

![1](https://user-images.githubusercontent.com/10832568/45076267-4e8f1280-b11c-11e8-8678-20afc00b65e5.jpg)

**Comment by NaNraptor** [comment]
That's the problem then :) I will see if I can fix it

**Comment by NaNraptor** [comment]
[UFB-4.5.1.1-Chinese.zip](https://github.com/UltimateFishbot/UltimateFishbot/files/2352284/UFB-4.5.1.1-Chinese.zip)

Try this and let me know if it works :)

**Comment by Crystalleaf** [comment]
Yes it worked! Thank you!

**Comment by NaNraptor** [comment]
No problem, it's what I'm here for :)

**Comment by NaNraptor** [comment]
@Crystalleaf my I kindly ask you to create a Chinese translation for us? In case you have the time and willingness of course :)

**Comment by Crystalleaf** [comment]
@NaNraptor No problem. Just tell me how to make it~

**Comment by daniel-widrick** [comment]
https://github.com/UltimateFishbot/UltimateFishbot/blob/CSharp/UltimateFishBot/Resources/English.xml

A version of that file with all of the text enclosed in <tags>Translate Me!</tags> would be what we need.
