### ISSUE TITLE
no start /stop

### ISSUE THREAD

**Issue by mcousins2009** [UltimateFishbot/UltimateFishbot#142]
I am having issue with the fact on my copy that the start stop is disabled... I dual monitor and using my ctrl+shift+s is extremely important... been using this for over 3 yrs ..please fix it ....pretty plz ...i got fish to catch

**Comment by NaNraptor** [comment]
Did you download the compatibility version? If so please download the other one.

On compatibility version this shortcut is disabled

**Comment by NaNraptor** [comment]
Here is the link for your convenience https://github.com/UltimateFishbot/UltimateFishbot/releases/download/4.5.1.0/UFB-4.5.1.0.zip

**Comment by NaNraptor** [comment]
Should he resolved. Closing the issue
