### ISSUE TITLE
when using steam streaming

### ISSUE THREAD

**Issue by Joelyboy** [UltimateFishbot/UltimateFishbot#143]
the Prog wont run.

says wow must be open 

but im streaming to my other pc.

any info on this?

**Comment by NaNraptor** [comment]
Hey, come back on discord, I forgot to mention something :D

**Comment by guitaristanime** [comment]
Did you fix this, I wanted to use this via steam streaming.
Tried changing the proc name in the config file but it's just ignored.

I tried to compare what was changed for the chinese version but the config file is exactly the same.

I then opened the C# source code in VS but I dunno what I'm doing, I can't code really.

Any help on how I can get it running via Steam In-Home Streaming?

The process name is "streaming_client" and the Window title is "World of Warcraft (Streaming)"

**Comment by NaNraptor** [comment]
Streaming is not supported and probably won't be as it requires a major rework
