### ISSUE TITLE
Need some help and have questions

### ISSUE THREAD

**Issue by KrazyTurk** [UltimateFishbot/UltimateFishbot#145]
Hello eveyone,
I've used UFB before, especially in WoD... but I feel like I'm missing something here
I see that there is a launcher thing that somehow tells you if it's safe to use or not? and also it said something about the process name being changed every time you launch, but my process still say UltimateFishbot.exe which seems concerning from a detection standpoint...
I was trying to message one of the devs on here directly, but it seems I can't do that. Any of you "in the know" use a discord or something we could chat on? or come to my guilds discord?

**Comment by NaNraptor** [comment]
Hi there, the discord is https://discord.gg/CyqtMYF
