### ISSUE TITLE
1 of my 3 computers cant see the icon change. And using the other option really sux.. 

### ISSUE THREAD

**Issue by Apful** [UltimateFishbot/UltimateFishbot#150]
Title. How come some computers cant see the icon change? Is it about windows? Or is it about the gfx card? Any way to fix this?

Thx for answers i get.

**Comment by Apful** [comment]
Also, if the mous could only operate inside of the set search area, this wouldnt be so bad, but when using the option to not search by icon change the mouse jumps around to any chiny thing it can find on the hole screen 80% of the time instead of finding the bobber.

**Comment by NaNraptor** [comment]
Could you describe what "can't see" means? Does it not work? What specifically is happening to make you think it doesn't?

Also what version of Windows are you using in each of the 3 computers? Once I have this information I should be able to help you. 

Finally I don't think I understood what you mean with your second comment :D sorry

**Comment by Apful** [comment]
What i mean is that i have to uncheck the "check cursor icon" and that says "may not work on some computers, disable if the bot doesnt find the bobber" And that is spot on. It just serarches if i have the normal setting turned on, even when the icon changes when above the bobber it just pass by.

I have W10 on all 3.

**Comment by sp3sh** [comment]
Well simply put it won't work on all systems, that's why the option exists in the settings. When you do not choose mouse cursor its using pixel detection which means you need to set your graphics settings like any other pixel bot and make sure you are in a spot where day and night wont get you.

**Comment by Apful** [comment]
alright, it works kinda well when i find a good spot. I was mostly woundering why it doesnt work, if its based on the gfx card or some windows thing that you need to download or whatever, but i gues you dont know then?

**Comment by NaNraptor** [comment]
As @sp3sh said it just doesn't work in some computers... So yeah we don't know :)

**Comment by maksimlya** [comment]
Hi, i just had the same issue, the thing that caused that bug in my case was custom scale setting in windows 10 ( I had it at 110% for the windows icons look bigger). I set it back to 100% and the addon works flawlessly :). Can get to that setting by right click on desktop -> Display Settings -> Advanced Scaling Settings. Hope that helps.
