### ISSUE TITLE
It is not clicking when the splash happens

### ISSUE THREAD

**Issue by ryancp81** [UltimateFishbot/UltimateFishbot#151]
I too had some trouble getting it to cast but it eventually started working fine.  My issue is that it does not click to catch on the splash sound.  Thoughts?

**Comment by sp3sh** [comment]
Please read the instructions, all the troubleshooting tips you need are supplied. This is for program issues only - THIS IS NOT A FORUM.

**Comment by NaNraptor** [comment]
@ryancp81 for such issues please join our discord
