### ISSUE TITLE
Vanilla WoW 1.12

### ISSUE THREAD

**Issue by luuthor** [UltimateFishbot/UltimateFishbot#153]
I am having a problem with the the bot casting the pole and then finding the fish, any idea how to fix? No error message.

**Comment by NaNraptor** [comment]
With such problems, join the discord and ask the community. Here on github we can help you with bugs that break the bot

**Comment by luuthor** [comment]
What is your discord? Thank you.

**Comment by NaNraptor** [comment]
https://discord.gg/yPc5R8
