### ISSUE TITLE
Leaves the wow window

### ISSUE THREAD

**Issue by Alucard9000** [UltimateFishbot/UltimateFishbot#20]
I do not know what the problem is, but it seems that after you click on the wow window it does its normal business. Until it is time to recast, at some point it leaves the wow window and thinks it has pressed the button for casting. Every time it has to recast I have to click on the wow window for it to work for that one cast.

**Comment by Mograine** [comment]
A temporary fix is to use Wow in full screen

**Comment by Alucard9000** [comment]
i will give that a shot

**Comment by henrikhermansen** [comment]
@Alucard0100 do you have wow in windowed mode? If so make sure you don't use a too small resolution, and make sure the wow window is not moved from the initially centered position. I'm using it fine on 1600x900 on my full hd monitor.
