### ISSUE TITLE
Not Casting

### ISSUE THREAD

**Issue by dermicha1978** [UltimateFishbot/UltimateFishbot#25]
Hello,

i have done everything whats to do. It Casts the first time but then the bot only searches the lure and dont recast

**Comment by Xquette** [comment]
Hello, I agree, I do everything is on How to Use, But it doesn't cast the spell :/ Any help ? (When i cast the spell manually, it can pick up the fish etc..)

**Comment by henrikhermansen** [comment]
@dermicha1978 @Xquette can you take not of what the bot says while it is looting, and afterwards?

**Comment by alfo72** [comment]
I don't get a message but what I have noticed is that the application window bar (border at the top of the window) turns white after the first loot.  Under normal circumstance it is Orange so I assume the window is losing focus.

**Comment by henrikhermansen** [comment]
@alfo68 are you talking about the bot window or WoWs window appearing to lose focus?

**Comment by alfo72** [comment]
WoW.  I have it running fullscreen windowed now and it works perfectly but in windowed mode the WoW screen loses focus when the bot attempts to cast.

**Comment by Mograine** [comment]
It should now be fixed with the new C# version, just wait for the 4.0 update on the website, then please test again

If it's not fixed, feel free to open a new issue :)

**Comment by alfo72** [comment]
great programme by the way....700 skill, Nat as a follower....run it while I work!

**Comment by NekoKetsu** [comment]
Hi the bot using "shift +1" instead of "1" to cast fishing
How can i fix it ?
(when i start the bot, he change my action bar to the first, then start searching for the lure)
