### ISSUE TITLE
Wont Detect WoW

### ISSUE THREAD

**Issue by fatlittlewhiteguy** [UltimateFishbot/UltimateFishbot#29]
recently started playing wow again, then realized I needed some money, so I booted up my fish character so I could bot and get some fish to sell. then when all the settings were as required I pressed start and it said "Error Finding Game. Make sure you start the game before clicking 'Start' on the bot" then I checked if it was an old version, it was, so I updated, then tried again, same outcome, then I turned of a software that is a form of game add-on (overwolf) but the same, and now I'm here. please help be, this is really bothering me...

**Comment by henrikhermansen** [comment]
Had a look at #17 ?

**Comment by fatlittlewhiteguy** [comment]
yes i have, i tried it all, no result

**Comment by henrikhermansen** [comment]
I assume you're using the version 3.0 from the website. There was a possible fix added  a few days later in commit 44da6d1891a4d111ecb8c86b6841112ab9f2acba. I've built a fresh version from the latest commit point, including that fix. You can get it at http://www.henrikh.net/fishbot_3_1.zip. Please let me know if this solves your issue.

**Comment by fatlittlewhiteguy** [comment]
thank u so much, u really helped me there, keep being awesome!
