### ISSUE TITLE
Bait and lure not working

### ISSUE THREAD

**Issue by Alpheratz57** [UltimateFishbot/UltimateFishbot#32]
Hi, everything is working great, but not luring and baiting. I have chosen 'USe Alt-Key modifier' to bind lure (Alt+1) and bait (Alt+6), but nothing happens
Cast key worlks fine (Alt+0]

**Comment by henrikhermansen** [comment]
@Ebola57 this sounds somewhat similar to #38 . Have a look at that thread and see if it provides you with a solution.

**Comment by Mograine** [comment]
Closed for duplication, feel free to open a new issue if needed
