### ISSUE TITLE
Preventing 'away' state. 

### ISSUE THREAD

**Issue by sauronazm** [UltimateFishbot/UltimateFishbot#34]
Will be a good improvement to implement logic for preventing 'away' state? The reason: when I'm in 'away' state, I got a lot of spam-messages. I think simple jumping or moving left-right will be enough. Or there is an option in WoW for that which I missed? =)

**Comment by henrikhermansen** [comment]
Are you actually put in afk state while fishing? I haven't really thought about it before, but I haven't noticed that I've gone afk while fishing either.

**Comment by sauronazm** [comment]
Hi! Yes, I always put in afk state while fishing if I don't move my character. However I do not disconnect from the server. Don't know, probably it is server specific behavior. Would be great to know if anybody else has the same issue.

**Comment by Mograine** [comment]
I used it only on officials server and never get the "Away" state, do you use it on a private server ?

I saw that you already started to code this enhancement in VB, do you need some help to convert it in C# ?

**Comment by sauronazm** [comment]
I'm playing on official server. I don't think that my modification should go into mainstream because it looks like nobody has the same problem =) @UltimateFishbot, please close that ticket if you think so.

**Comment by Mograine** [comment]
The advantage of settings is that you can disable what you don't need :)

Closed by c8ddaf292cf49ab4886785b73ed93e573baf4d6e
