### ISSUE TITLE
Won't click when the bobber splashes.

### ISSUE THREAD

**Issue by Manjamad** [UltimateFishbot/UltimateFishbot#37]
I have the audio devices on both the program and WoW set to the same device. I have tested to see that the sounds in the game are being heard by the program, the green bar moves to 10-90 depending on what i'm doing. Still isn't clicking the bobber when a fish bites. Any suggestions?

**Comment by dmccrevan** [comment]
Is every other feature working correctly?

**Comment by Manjamad** [comment]
Hard to tell without it clicking. But it casts, and moves and stops on the bobber, it just doesn't click when it splashes. I've set thresh hold to 1, changed all audio settings, etc.

**Comment by dmccrevan** [comment]
That's really weird...never ran into this problem myself...did you try just removing it from your pc then downloading it again?

**Comment by Manjamad** [comment]
Would you believe... that worked...
