### ISSUE TITLE
Invalid hotkey to start/stop the bot

### ISSUE THREAD

**Issue by henrikhermansen** [UltimateFishbot/UltimateFishbot#41]
Maj is not a valid key on the keyboard. As far as I understand this is actually the Shift key. With Ctrl+Maj+S I get an exception when trying to launch the bot. If I change it to Ctrl+Shift+S I have no problems running it. Does it work for your French setup if you change this to Ctrl+Shift+S @Mograine ?

**Comment by Mograine** [comment]
Yup it's in fact a french specific name, sorry for that. Shift work perfectly for me
