### ISSUE TITLE
Risk of Detection [Question]

### ISSUE THREAD

**Issue by SpencerCarstens** [UltimateFishbot/UltimateFishbot#42]
Hello All,

First of all, thank you for making and maintaining this. 

Obviously, there is no real "safe" bot solution, but I'm curious on your views on the chance of detection.

Also, are there any recommended practices or pointers for limiting the risk while using the bot?

Thank you for your time.

**Comment by henrikhermansen** [comment]
This question has been asked before, have a look in #35 . To sum it up: we have noe reason to believe Warden is aware of the bot, as we haven't seen any mass banning of users. There has been one banned user we're aware of, but he left his account online 24/7. He didn't fish around the clock, he did other stuff too, but I guess Blizzard gets rather suspicious when you never go offline...

I'd recommend you make sure your amount of online time is realistic. Whether Blizzard has any thresholds of online time in a day or in a week which will call their attention is unknown. In my own experience I've had no trouble fishing while at work 5 days in a row, and then doing other stuff in the afternoon and the weekend. Also try to stay out of the mot crowded places, as players might get suspicious and report you aswell, if they see you fish for hours without responding in chat.

**Comment by SpencerCarstens** [comment]
Sounds good.

Thanks for the reply.
