### ISSUE TITLE
Fishbot doesnt loot.

### ISSUE THREAD

**Issue by dariuz93** [UltimateFishbot/UltimateFishbot#46]
as a tittle says.
Greetings

**Comment by henrikhermansen** [comment]
Do you have either the auto looting enabled ingame or the shift-loot setting enabled in the bot? Also make sure you don't have both enabled.
If the above mentioned settings seem correct, could you describe a bit more closely what happens? What does the bot say in its window?

**Comment by dariuz93** [comment]
I fix it, was my problem.
Thanks for all

**Comment by henrikhermansen** [comment]
No problem :+1:
