### ISSUE TITLE
works fine but...

### ISSUE THREAD

**Issue by seylonk** [UltimateFishbot/UltimateFishbot#50]
all seems to be work, but i need that when rightclick to open the loot w8 1º sec and right click again. becouse autoloot in my servers dosent work for fishing. its just ignore fish.
edit: Shift autoloot dosent work to. i need to manualy right click to get loot

**Comment by henrikhermansen** [comment]
Have a look in #46 to make sure your settings are correct. Also have a look in #48 for an alternative solution using an autoloot addon.
If neither of these previous issues can aid you, please provide a bit more detailed info, like I requested from the reporter in #46.

**Comment by seylonk** [comment]
I resolved this problem with autoloot addon.
closed.
thanks
