### ISSUE TITLE
vanilla version

### ISSUE THREAD

**Issue by jimpanskor** [UltimateFishbot/UltimateFishbot#51]
hi there,

is there any version or way to get this working on a vanilla 1.12 server?

no matter what i try it doesnt start searching the blooper or it recasts fishing every 3 or 10 seconds still without searchin for the blooper and it doesnt care about the values i entered, its just kinda instarecast or at 10 seconds.
if i check spiral route the mousepointer gets stuck topleft.

regards jim

**Comment by LaBlazer** [comment]
This issue has been inactive for a long time, therefore i'm closing it... also i've checked this and its working in vanilla for me. Maybe try using the latest version if you are still having this issue...
