### ISSUE TITLE
Support for double click casting

### ISSUE THREAD

**Issue by gmillerd** [UltimateFishbot/UltimateFishbot#53]
Allow mouse clicks rather than keystrokes so addons like fishing buddy can do their thing with outfits/lures and such.

**Comment by chance87** [comment]
The add on supports lures already and if you wanted you could just have a macro for equip set "fishing" and tie it into a bind for apply charm, bait, lure etc...

**Comment by LaBlazer** [comment]
Answered by @chance87, closing issue
