### ISSUE TITLE
Won't cast or find bobber

### ISSUE THREAD

**Issue by chance87** [UltimateFishbot/UltimateFishbot#55]
i ran the application just fine one day and the next it stopped working. It says it's applying bait, lure, charm but it never casts the line. So I manually cast it and it won't find the bobber either. One thing I noticed is if I tab over to fishbot.exe it will start scanning for bobber. I haven't changed any settings and I even tried re-downloading the program. When I get home I'm going to try turning off all add ons to see if that helps. 

Thanks in advance!

**Comment by secreal** [comment]
you need place your fishing skill (fishing cast skill), to action bar position 1

**Comment by chance87** [comment]
It is... If you read what I wrote it was working just fine the next morning nothing changed not was anything moved. My friends have tried running theirs and it seems the not is no longer working for them either.

**Comment by NaNraptor** [comment]
Check latest version, that seem like a strange issue, but that was a long time ago
