### ISSUE TITLE
UltimateFishbot has stopped working

### ISSUE THREAD

**Issue by Misaio2** [UltimateFishbot/UltimateFishbot#56]
so it worked before but now after I closed the program and closed WoW to go to RL stuff this happens.
I opened WoW before I opened the bot and did everything as I did before now I got: 
Problem signature:
  Problem Event Name:   CLR20r3
  Problem Signature 01: ultimatefishbot.exe
  Problem Signature 02: 1.0.0.0
  Problem Signature 03: 54ce19bd
  Problem Signature 04: System.Windows.Forms
  Problem Signature 05: 4.0.30319.34251
  Problem Signature 06: 54daee67
  Problem Signature 07: 425f
  Problem Signature 08: 4b
  Problem Signature 09: System.ArgumentOutOfRange
  OS Version:   6.1.7601.2.1.0.768.3
  Locale ID:    1033
  Additional Information 1: 0a9e
  Additional Information 2: 0a9e372d3b4ad19135b953a78882e789
  Additional Information 3: 0a9e
  Additional Information 4: 0a9e372d3b4ad19135b953a78882e789

I tried completely deleting it and reinstalling it, after redownloading it and I still get the same errors. I literally changed nothing from before it threw errors. HALP!

**Comment by mcousins2009** [comment]
Yeah it does not work any better with windows 10 either

**Comment by LaBlazer** [comment]
Try compiling the newest version and if the issues still presist open a new issue.
