### ISSUE TITLE
Newb question

### ISSUE THREAD

**Issue by Ghostops117** [UltimateFishbot/UltimateFishbot#58]
just trying to figure out how to get this up and running, i apologize for the n00b question

**Comment by LaBlazer** [comment]
What cant you get running? Just compile it, run WoW, add fishing and lure to your hotbar, calibrate the volume detection and run it... Can you be more specific what cant you get running??

**Comment by FireEmerald** [comment]
@LaBlazer Shouldn't this issue been closed?

**Comment by LaBlazer** [comment]
@FireEmerald True, i missed this issue... Closing.
