### ISSUE TITLE
windows 10

### ISSUE THREAD

**Issue by mcousins2009** [UltimateFishbot/UltimateFishbot#59]
Can you please hurry and make this program compatible with windows 10.. i cant fish,,lol

**Comment by LaBlazer** [comment]
We cant fix it for win10 if we dont know what is not working... Describe your problem more... What does happen when you run it? Which version are you trying to run? Did you compile it yourself?....

**Comment by mcousins2009** [comment]
I am running the most current version and it does nothing it won't open or anything.  I have tried rolling back my NETFRAME back to 4.5  but it still didn't open it..ran it in compatibility  mode and it doesn't work also was running it as both administrator and non and still nothing.  I get nothing it doesn't  do anything but when I roll back to my old windows it works wonderfully

-------- Original message --------

**Comment by LaBlazer** [comment]
On my win 10 it works just fine, so idk... Ill try to investigate this issue
..

**Comment by mcousins2009** [comment]
What windows 10 are you using

-------- Original message --------

**Comment by LaBlazer** [comment]
Win 10 for insiders, ive been insider for 3 months now...
EDIT: Try running this: https://onedrive.live.com/redir?resid=8BC0A63EE379915B!364&authkey=!ABBnjnQ8idp5uLA&ithint=file%2czip

**Comment by Nactishe** [comment]
Hmmmm... it doesn't seem to be recognizing when the fish is caught after the first success. I see Heard a fish, then every time after that nothing.. works fine in win7

**Comment by LaBlazer** [comment]
This may be the same issue as in #61 , i will message him about the code...

**Comment by Romain-dev** [comment]
Very good job for your bot.
Unfortunatly it don't work on windows 10 x64.
I reformated my computer for an other reason and now it works (windows 8.1 x64).

More informations: on windows 10 it don't work at all with dual screen.
With native screen I miss 90% of fish.
The problem seems to be that it don't detect my audio output and don't click when I catch a fish.

Thanks to your job.

**Comment by NonQuixote** [comment]
This hasn't been closed so I'm assuming that it's still an issue for at least Romain.  While I can't offer a solution I will say that I use the bot on W10 Pro x64, with dual monitors and I have yet to encounter the problems that Romain listed.  The bot casts, seeks the lure and retrieves the catch on splash.

I'm running WoW in 64 bit mode, windowed on the primary screen with all the ingame settings recommended by the bot's section "How To Use".

**Comment by StefanZivanovic** [comment]
Hello guys. I have a problem with the Fishing bot, i'm using the windows 10 and my operating system is 64bit.

Problem is in cursor, when i hit start my cursor is stuck in upper left corner and wont move, anyone know whats wrong?

**Comment by Gasur** [comment]
@StefanZivanovic You can start by giving information the developers can use. What version of the game? What local language? What OS language? Has it worked for you before?

Also, it seems like [this](https://github.com/UltimateFishbot/UltimateFishbot/issues/30#issuecomment-182583718) works just fine.

**Comment by StefanZivanovic** [comment]
Its wotlk 3.3.5 english for both. Only when i was on win7.

My cursor is stucked in upper left corner and keeps there even if i try to move mouse.

**Comment by StefanZivanovic** [comment]
I don't know what to do in that link you provided. I have teamviewer if anyone is willing to help me by doing it please do.

**Comment by Panda813** [comment]
Always throwing a .Net Framework Error... I have emailed about this issue once before and never got it resolved... I love the bot but what is the point of it if I have to babysit it??? Windows 10 Home OS.. Something about JIT Debugger... IDK anything about it and the internet doesnt have nothing to help me resolve my issue... Plz help it is very annoying...

**Comment by elzii** [comment]
Confirming that I have the same issue as @StefanZivanovic. Cursor is stuck at very top left on screen on Windows 10.

**Comment by NaNraptor** [comment]
Fixed in latest release

**Comment by NonQuixote** [comment]
You rock
