### ISSUE TITLE
been working perfactly now it isnt 

### ISSUE THREAD

**Issue by omeganate** [UltimateFishbot/UltimateFishbot#60]
i was fishing a few days ago and it was working fine but when i went in to it today when i minimized wow it would would do the lines up and done but the min i go back into the game it does nothing not even the lures or anything idk why is it not working??? PLEASE HELP!!!

**Comment by LaBlazer** [comment]
have you tried restarting your computer/bot/wow??

**Comment by omeganate** [comment]
It was a setting on my computer that was the problem but I got it to work thank god!!

Sent from Yahoo Mail on Android

**Comment by LaBlazer** [comment]
Ok, thats good to know... now only if I had privileges to close Issues...

**Comment by LaBlazer** [comment]
Solved, therefore im closing the issue.
