### ISSUE TITLE
Doesn't cast fish skilling

### ISSUE THREAD

**Issue by jmdhave** [UltimateFishbot/UltimateFishbot#64]
It's right in #1 key and i follow all the procedure from "how to use it" but it doesn't work :(((  can you help me ?

if i put any spell in #1 it doesn't cast it either?
Is there anybody here ??

**Comment by FireEmerald** [comment]
That's not a forum this is the bug tracker. If you have problems with the application you should debug it on your own and then create a ticket here with a bunch of more exact informations.
