### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Panda813** [UltimateFishbot/UltimateFishbot#65]
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.ArgumentException: Keyword "" is not valid.
   at System.Windows.Forms.SendKeys.ParseKeys(String keys, IntPtr hwnd)
   at System.Windows.Forms.SendKeys.Send(String keys, Control control, Boolean wait)
   at System.Windows.Forms.SendKeys.Send(String keys)
   at UltimateFishBot.Classes.Helpers.Win32.SendKey(String sKeys) in c:\projects\ultimatefishbot\UltimateFishBot\Classes\Helpers\Win32.cs:line 165
   at UltimateFishBot.Classes.BodyParts.Hands.DoAction(NeededAction action, Mouth mouth) in c:\projects\ultimatefishbot\UltimateFishBot\Classes\BodyParts\Hands.cs:line 114
   at UltimateFishBot.Classes.Manager.HandleNeededAction(NeededAction action) in c:\projects\ultimatefishbot\UltimateFishBot\Classes\Manager.cs:line 357
   at UltimateFishBot.Classes.Manager.TakeNextAction(Object myObject, EventArgs myEventArgs) in c:\projects\ultimatefishbot\UltimateFishBot\Classes\Manager.cs:line 306
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

UltimateFishBot
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/Wickidclown.Wickidclown-PC/Programs/WOW/UltimateFishBot.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34251 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34270 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34238 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34234 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

CoreAudioApi
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/Wickidclown.Wickidclown-PC/Programs/WOW/CoreAudioApi.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.34209 built by: FX452RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by Panda813** [comment]
How do i fix this??

**Comment by LaBlazer** [comment]
You didn't gave much information... When does this error occur? What version are you using?? Did you try to enable JIT debugging?? If you don't know, how to do this then you should probably download the newest version and not worry about compiling...

**Comment by Panda813** [comment]
it occurs after about 20-30 mins into fishing... i am using the lastest
version you have to download... i do not know how to enable JIT debugging

**Comment by NaNraptor** [comment]
Try using latest release if you are still using the bot
