### ISSUE TITLE
It dosen't catch a fish.

### ISSUE THREAD

**Issue by endyleo** [UltimateFishbot/UltimateFishbot#68]
Hello.
I'm using UltimateFishBot v4.1.

I clicked "Start" button and I thought it works perfectly. 
But when there was a catch-sound, the program says "I hear a fish", but it doesn't click on it.
And the program goes to another casting immediatly.
So I couldn't got a fish. 

How could I fix this?

**Comment by TonyVallad** [comment]
As I said in https://github.com/UltimateFishbot/UltimateFishbot/issues/8, it hears the fish, and it seems it doesn't click or clicks too late, no way to know at this time.

Not a problem of sound detection or of autolooting.

**Comment by stricee** [comment]
Have same problem im using windows 10 x64 bit (with cortana enabled if that matters). I didnt test it on my laptop witch runes win7 x32bit
