### ISSUE TITLE
WoW 1.12.1 not stopping at bobber

### ISSUE THREAD

**Issue by dkcas11** [UltimateFishbot/UltimateFishbot#69]
Hi,

I have tried to get the bot working on both Win 7 Ultimate and Win 10 Pro N, with version 4 and 4.1.
4.0 had the cursor stuck in the upper lefthand corner. No matter what i did, it didn't move at all.
4.1 (and 4.1.0.1) had the same issue, except the bot moved the cursor correctly, to find the bobber, only when i specified the area. This was perfectly fine, and a nice feature.

But now two new issues came.
The first one: The bot couldn't detect the bobber, when the cursor changed. 
The second: The bot detected the bobber "Check cursor icon" was disabled, although 9/10 times wouldn't search for the bobber. Sometimes it did. I tried to check whether it was because i moved my mouse a little or not, but i am unsure.

So a combination of those two would make it work it seems. Although, after posting this issue, it seems it will not loot the bobber either. Tried setting the Threshold to all kinds of stuff. Both low and high, from 5-40.

I am running a vanilla client of patch 1.12.1, the same as Feenix and Nostalrius servers. Does this change how the bot detects the cursor change at all? Or do you know how well the bot supports earlier patches? If you need a client to test out, here is the one provided by Nostalrius https://mega.nz/#!OwQz3TzI!xKn8WteFKKVJtn57iByBWgRzRh51PYEQSw1dcWEjyGg

I found another funny bug. When specifying the area, and the instructions comes up, i push Enter, and the box goes away (i assume it's on 'pressed') and just as the box closes, the overlay comes and goes away (and here i assume it's due to Enter being 'released'). Just something minor i found :)
- Casper

**Comment by LaBlazer** [comment]
Hello, thanks for the bug report. I'm sorry, but i don't have much free time now, I'll try to fix it later... I don't know when, but I'll try to find some free time :)

**Comment by stricee** [comment]
I also play on wow 1.12 version so Fixing this would be much appreciated!! :)

**Comment by Dids** [comment]
Any news on this?

**Comment by beren12** [comment]
any?

**Comment by NaNraptor** [comment]
Try latest version, should fix this problem
