### ISSUE TITLE
AFK mode on dev release

### ISSUE THREAD

**Issue by jensskott** [UltimateFishbot/UltimateFishbot#72]
Seems afk mode is crashing the application every times it tries.

**Comment by GrenderG** [comment]
Yeah I have noticed it too. 

![captura](https://cloud.githubusercontent.com/assets/8654362/13018607/c29710b2-d1ca-11e5-8d85-75ab4a167d7c.PNG)

**Comment by evilpookie** [comment]
Has anyone tried a seperate afk bot to run while fishbot runs?

**Comment by daniel-widrick** [comment]
I am unable to reproduce this issue so far.

**Comment by NaNraptor** [comment]
me neither... A separate anti-afk bot should work just fine this one

Closing this for now
