### ISSUE TITLE
Just this week....

### ISSUE THREAD

**Issue by alfo72** [UltimateFishbot/UltimateFishbot#73]
Double clicking shortcut doesn't run.  Thought it might be a detection issue because if you rename it works.

Application: UltimateFishBot.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at CoreAudioApi.Interfaces.IMMDeviceEnumerator.GetDevice(System.String, CoreAudioApi.Interfaces.IMMDevice ByRef)
   at CoreAudioApi.MMDeviceEnumerator.GetDevice(System.String)
   at UltimateFishBot.Classes.BodyParts.Ears..ctor(UltimateFishBot.Classes.Manager)
   at UltimateFishBot.Classes.Manager..ctor(UltimateFishBot.frmMain)
   at UltimateFishBot.frmMain..ctor()
   at UltimateFishBot.Program.Main()

Log Name:      Application
Source:        Application Error
Date:          31/01/16 22:01:04
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      MainPC
Description:
Faulting application name: UltimateFishBot.exe, version: 1.0.0.0, time stamp: 0x54ce19bd
Faulting module name: KERNELBASE.dll, version: 10.0.10586.0, time stamp: 0x5632da1c
Exception code: 0xe0434352
Fault offset: 0x000bd8a8
Faulting process ID: 0x1af0
Faulting application start time: 0x01d15c16ad7e253b
Faulting application path: C:\Users\Downloads\Fishbot\UltimateFishBot.exe
Faulting module path: C:\WINDOWS\SYSTEM32\KERNELBASE.dll
Report ID: 4eacb420-b29a-40ca-9388-fc1b8a1ef57b
Faulting package full name: 
Faulting package-relative application ID: 
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-01-31T11:01:04.144652900Z" />
    <EventRecordID>6935</EventRecordID>
    <Channel>Application</Channel>
    <Computer>MainPC</Computer>
    <Security />
  </System>
  <EventData>
    <Data>UltimateFishBot.exe</Data>
    <Data>1.0.0.0</Data>
    <Data>54ce19bd</Data>
    <Data>KERNELBASE.dll</Data>
    <Data>10.0.10586.0</Data>
    <Data>5632da1c</Data>
    <Data>e0434352</Data>
    <Data>000bd8a8</Data>
    <Data>1af0</Data>
    <Data>01d15c16ad7e253b</Data>
    <Data>C:\Users\Downloads\Fishbot\UltimateFishBot.exe</Data>
    <Data>C:\WINDOWS\SYSTEM32\KERNELBASE.dll</Data>
    <Data>4eacb420-b29a-40ca-9388-fc1b8a1ef57b</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by NaNraptor** [comment]
No idea what might have caused that, please use latest version and report back :)
