### ISSUE TITLE
How should i get this going.

### ISSUE THREAD

**Issue by teonancatl** [UltimateFishbot/UltimateFishbot#75]
So I was able to download the zip file and unzip it. I can open the exe file. but as I continue to read the forums here, I see that running that generic file will probably get me detected by warden. Now I don't know any C# my programming experience is limited to a C++ class I took in college.... that being said, I figure if all I need to do is get a compiler up and going then edit that assemblyinfo.cs file before I compile it...I could probably manage...?

so what steps can I take to get this moving.
1) compiler options?
2) I see there are different fishing addons that would reduce the programming needed. what fishing addon is recommended?
3) There seem to be multiple files with different source code. what files would I need to compile to get a skeleton version running that would be complimented by the recommended fishing addon?
4) other stuff that I don't get but need to know...

thanks for your time concerning this.

**Comment by muzza01** [comment]
Would love an answer to this as well please :(

**Comment by Mograine** [comment]
Hello,

Sorry about the delay. You just need to download Visual Studio Community Edition (it's free), open the project, modify the assemblyinfo.cs and then click on "Generate", it's as easy
