### ISSUE TITLE
Not clicking on caught bobber all the time.

### ISSUE THREAD

**Issue by lefishes** [UltimateFishbot/UltimateFishbot#78]
Hello, I just got the program and am trying to get it working 100%.  I have all the sound settings up and auto loot on.  It seems like about half the time, the program won't hear the bobber when a fish is caught.  Sometimes it works correctly and others it just sits there and times out until the next cast.  

Also, the sound settings are all that matter right?  Independent of the speaker actually being turned on?  So if I wanted to, I could have the speakers off and the sound settings high and it should still work... as it's not using the microphone or anything to detect sound, etc...?

Thanks.

**Comment by hepafleb2** [comment]
For me to ensure the sound isnt the problem i have the overall  sound, sound of the app in the system tray, and sound in the game itself all turned up to 70-100% otherwise it wont _hear_ it.

**Comment by lefishes** [comment]
So apparently I had two sound apps in the system tray.  Both were maxed, but one had the submenu with the wow app at half volume.  I cranked that up and now it's working great.
Thanks to you and everyone else how has contributed to this program!

**Comment by Gasur** [comment]
It is very important to note, that the game volume and the volume in the bot settings has to cross. Meaning if the bot setting requires the volume to be at 80%, and you have your game volume on 20%, it will never reach that threshold. A good way of debugging it, is take Windows volume to max, game volume to max & bot setting to 1 or any low number.
