### ISSUE TITLE
Cursor just goes to the top left of the screen

### ISSUE THREAD

**Issue by Dormire** [UltimateFishbot/UltimateFishbot#79]
Seems to work fine otherwise.  After it casts the cursor moves to the top left of the screen and doesn't move.  If I manually move it over the mouse it does not catch the fish.  The program says I hear a fish but always a couple seconds after the bobber sound.  I am running on a 2.4.3 private server

**Comment by peasant** [comment]
same problem. cursor stuck to the top left.

**Comment by crimmson** [comment]
Same problem, the cursor just stays in the top left corner and the bot just restart fishing over and over again

**Comment by flinxsl** [comment]
I am having this problem too.  I downloaded the source code and ran it in debug mode and found that the GetWowRectangle() function is not working.  It returns verticies 0,0,0,0.  This might be related to 32 bit vs 64 bit windows...
