### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by mlande5** [UltimateFishbot/UltimateFishbot#82]
Unhandled exception has occurred in your application. If you clock continue the application will ignore this error and attempt to continue. If you click Quite the application will close immediately. Object reference not set to an instance of an object. 

I can tell you clicking continue just repeats the same message.  This worked flawlessly two nights ago without a single hiccup.  

Program is running then I launch your app.  Running W10 64 bit with 48 GB of RAM and 4GB Video Card. I did have some windows updates but it was for Office 2016 and nothing to do with W10 updates. 

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CoreAudioApi.Interfaces.IMMDevice.Activate(Guid& iid, CLSCTX dwClsCtx, IntPtr pActivationParams, Object& ppInterface)
   at CoreAudioApi.MMDevice.GetAudioMeterInformation()
   at CoreAudioApi.MMDevice.get_AudioMeterInformation()
   at UltimateFishBot.Classes.BodyParts.Ears.ListenTimerTick(Object myObject, EventArgs myEventArgs) in c:\projects\ultimatefishbot\UltimateFishBot\Classes\BodyParts\Ears.cs:line 40
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

UltimateFishBot
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/mike/Desktop/fish/UltimateFishBot.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

CoreAudioApi
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///C:/Users/mike/Desktop/fish/CoreAudioApi.DLL

System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1590.0 built by: NETFXREL2
##     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by UnLachy** [comment]
This is happening to me too. Any fix?

**Comment by UnLachy** [comment]
As a quick fix, once I turned off 'anti-afk' this stopped happening

**Comment by mlande5** [comment]
Hi that's good to know. I will try that tonight and see what happens.  

```
  From: UnLachy <notifications@github.com>
```

 To: UltimateFishbot/UltimateFishbot UltimateFishbot@noreply.github.com 
Cc: mlande5 mlande5@yahoo.com; Author author@noreply.github.com
 Sent: Monday, August 22, 2016 5:08 AM
 Subject: Re: [UltimateFishbot/UltimateFishbot] Unhandled Error (#82)

As a quick fix, once I turned off 'anti-afk' this stopped happening—

**Comment by mlande5** [comment]
Well I turned off the anti-afk and I still have the issue.  So sadly that wasn't the fix for me. 

```
  From: UnLachy <notifications@github.com>
```

 To: UltimateFishbot/UltimateFishbot UltimateFishbot@noreply.github.com 
Cc: mlande5 mlande5@yahoo.com; Author author@noreply.github.com
 Sent: Monday, August 22, 2016 5:08 AM
 Subject: Re: [UltimateFishbot/UltimateFishbot] Unhandled Error (#82)

As a quick fix, once I turned off 'anti-afk' this stopped happening—

**Comment by mcousins2009** [comment]
Same problem even with anti afk turned off.... i am so irritated..lol

**Comment by JLDNetwork** [comment]
goto AppData > Local > UltimateFishBot ... Inside you should find another folder, then 1 more... keep going until you get to a file called, user.xml. delete that file and restart the program. DO NOT enable anti-afk.

**Comment by mlande5** [comment]
Hi Jeff,
Ok so I didn't find a user.xml but a user.conf and deleted that.  
So now it's WORKING!!!!!!
Thank you very much
Mike

```
  From: Jeff <notifications@github.com>
```

 To: UltimateFishbot/UltimateFishbot UltimateFishbot@noreply.github.com 
Cc: mlande5 mlande5@yahoo.com; Author author@noreply.github.com
 Sent: Tuesday, September 27, 2016 10:26 AM
 Subject: Re: [UltimateFishbot/UltimateFishbot] Unhandled Error (#82)

goto AppData > Local > UltimateFishBot ... Inside you should find another folder, then 1 more... keep going until you get to a file called, user.xml. delete that file and restart the program. DO NOT enable anti-afk.—

**Comment by NaNraptor** [comment]
Apparently fixed, closing
