### ISSUE TITLE
About hearing the sound

### ISSUE THREAD

**Issue by ayurai** [UltimateFishbot/UltimateFishbot#85]
Windows can show in mixer, sound of wow separated of others, is not possible to make the program  hear the sound ONLY of wow ?

**Comment by NaNraptor** [comment]
This is a good point, I will find a way to do this. It is indeed annoying that you cant even listen to music while botting :)

**Comment by NaNraptor** [comment]
Unfortunately it seems that no api currently supports reading a single audio stream.

More on the topic here: https://social.msdn.microsoft.com/Forums/en-US/86b605b2-17d3-4576-9570-a16bc8a710cf/hook-audio-buffers-of-windows-application-individually?forum=windowspro-audiodevelopment

**Comment by daniel-widrick** [comment]
As an aside, I usually set the bot and wow to use a specific sound device not hooked to anything. EG. A sound device not attached to your headset.
