### ISSUE TITLE
bot completely not working

### ISSUE THREAD

**Issue by MERIZH1** [UltimateFishbot/UltimateFishbot#86]
Hello, its not about the .net etc. i got that all,
but but the bot is randomly not working, everytime something other fails.

playing on a vanilla wow privat server, does it matther?

**Comment by NaNraptor** [comment]
using a private server (and therefore private client) might cause an issue. Could you provide me with the name of the WoW client window?

**Comment by NaNraptor** [comment]
If an error occurs again reopen this issue
