### ISSUE TITLE
Fishing Ace Option

### ISSUE THREAD

**Issue by qwksilver** [UltimateFishbot/UltimateFishbot#91]
It's been around a long time, kinda surprised this isn't in the config screen.  Fishing Ace uses double right click to fish, or if bait is expired use the bait, etc.  The only thing it won't use is my fishing hat, that's an ace problem not this mod.

My Request is to add a move center screen, double right-click, instead of a cast key.
with an option in the settings to "use Fishing Addon"

**Comment by Gasur** [comment]
All that for very little benefit. I highly doubt it will be added. It does not take much effort to move your fishing key to your action bar.

**Comment by qwksilver** [comment]
Actually the benefit is huge, yes i can drop a lure here, or a fishing macro there on the action bar.  BUT casting with the double-rightclick of ALL the fishing addons, auto checks and reapplies bait if available, it also applies other things like the best available fishing buff (from rod or hat).  this mod is timer controlled, and can't make choices based on statuses.  so adding an additional trigger, one that is quite common, would likely be appreciated by many.

**Comment by NaNraptor** [comment]
Hopefully solved, closing until someone decides to revive it :)
