### ISSUE TITLE
Dying after a while

### ISSUE THREAD

**Issue by Radi038** [UltimateFishbot/UltimateFishbot#94]
Hi all,

At several occassion my bot starts running into the water and he is dying to drowning. Any idea how to fix this?

Thanks in advance.

**Comment by gmillerd** [comment]
You have click to move enabled likely and when you mouse misses the bobber you run to the mouse position. Similarly, if a npc/character runs in front of the bobber when you click occurs you will likely interact with them.

/run if GetCVar("Autointeract")=="0" then ConsoleExec("Autointeract 1") else ConsoleExec("Autointeract 0") end
