### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by ohlrie5b** [UltimateFishbot/UltimateFishbot#95]
Just curious if this still works.

**Comment by jacoblusk** [comment]
Yes, it does.

**Comment by Baronrobber** [comment]
Silly question but the zip i donwloaded has no .exe am i suppose to compile this ? if so how or am i just missing something

**Comment by jacoblusk** [comment]
@Baronrobber Yes you're supposed to compile it.

**Comment by Baronrobber** [comment]
Thanks for the response.. No idea how to do that .. so off i go..

**Comment by Gasur** [comment]
https://github.com/UltimateFishbot/UltimateFishbot/releases Here are some packaged versions. They are though slightly outdated, but should work regardless.

**Comment by Baronrobber** [comment]
thanksman

**Comment by NaNraptor** [comment]
Check out the latest one :)
