### ISSUE TITLE
Help with Server side issue.

### ISSUE THREAD

**Issue by sacreno** [UltimateFishbot/UltimateFishbot#98]
Is there a way to make the bot "left click after splash" in order to fix the issue on some private servers that auto loot does not work? The bot loots the splashed bobber but cannot auto loot the fish until you manually left click.

**Comment by Gasur** [comment]
Yes, if you code it. When you say left click, do you mean actual looting? Because I'm fairly sure the mouse has to move as well

**Comment by sacreno** [comment]
I am no programmer sad to say. The bot works perfectly until it tries to get the items from loot. it loots the splash but it leaves the loot window open at mouse position but does not take anything. The server we are on has auto loot on all things but gathering things (fish, ore and herbs)

So what I am asking is if someone could write a bit of code or point me in the right direction of learning how it could be done. 

It seems simple in my mind to make it left click at the current pos of the cursor "after it clicks on the bobber". When the bot runs it DOES loot the splash but cannot pick up fish until we manually left click the mouse on the fish/loot. The cursor does not need to move at all as my in game setting has "open loot window at cursor.

Thx in advance for any help

**Comment by Gasur** [comment]
Take a look in the source code for the right click event. If you do not want the mouse to move, all you need to do, is add a sleep (wait timer) and then left click. But the server has done that as a shitty anti-ban.

**Comment by sacreno** [comment]
Well the only file i have found with mouse clicks is 
https://github.com/UltimateFishbot/UltimateFishbot/blob/CSharp/UltimateFishBot/Classes/Helpers/Win32.cs

This seems to be where we could change or add another click on the loot frame but I do not know how to change it.
I am currently looking at 
https://stackoverflow.com/questions/8272681/how-can-i-simulate-a-mouse-click-at-a-certain-position-on-the-screen
to make some sort of effort to add this in.

**Comment by gmillerd** [comment]
AutoLoot isn't part of the fishing bot, normally you would have this
already with /console autoLootDefault 1 or something that does the same
"UI" or a Fishing Helper Addon"​

**Comment by NaNraptor** [comment]
This is now an option in the bot. Another way to do it is to go to your in game menu and turn Auto Loot on (or use an auto looting addon)
